name: Deploy All Environments

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        strategy:
            fail-fast: false
            matrix:
                environment: [dev, sit, uat, perf, preprod, prod]
        uses: ./.github/workflows/rw-deploy.yml
        with:
            environment: ${{ matrix.environment }}
        secrets: inherit
