name: Reuasable Workflow 1

on:
    workflow_call:

jobs:
    job1:
        name: Test Reuasable Workflow 1
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node: [18, 20]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - name: Run tests
              run: |
                  echo "Running tests on ${{ matrix.os }} with Node.js ${{ matrix.node }}"

    job2:
        name: Test Reuasable Workflow 2
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run additional tests
              run: |
                  echo "Running additional tests on ubuntu-latest"
                  echo "This job was initiated by Reusable Workflow 1, using the ${{ github.workflow }} workflow"
                  echo "This workflow was called by the ${{ github.actor }} actor"
