name: Reusable Deploy

on:
    workflow_call:
        inputs:
            environment:
                description: "Deployment environment (e.g. dev, sit, uat, perf, preprod, prod)"
                required: true
                type: string

jobs:
    deploy:
        runs-on: ubuntu-latest

        environment: ${{ inputs.environment }}

        steps:
            - name: Display Environment

              run: |

                  echo "Deploying to:"
                  echo "${{ inputs.environment }}"

            - name: Show Variables

              run: |

                  echo "AKS_CLUSTER=${{ vars.AKS_CLUSTER }}"
                  echo "RESOURCE_GROUP=${{ vars.RESOURCE_GROUP }}"
                  ::warning::This is a warning message to indicate that the following variables are sensitive and should be handled with care.
